-- ScoreCrawl 리그별 배당 테이블
-- Supabase SQL Editor에서 실행 (Project → SQL Editor → New Query → 붙여넣기 → Run)

-- k_league_1
create table if not exists k_league_1 (
  id bigint generated by default as identity primary key,
  시즌 text not null,
  라운드 integer not null,
  날짜 text,
  시간 text,
  홈 text not null,
  홈순위 text,
  홈점수 text,
  원정점수 text,
  원정순위 text,
  원정 text not null,
  승 text,
  무 text,
  패 text,
  오버 text,
  오버라인 text,
  언더 text,
  핸디캡홈 text,
  핸디캡라인 text,
  핸디캡원정 text,
  created_at timestamptz default now(),
  unique(시즌, 날짜, 시간, 홈, 원정)
);

-- k_league_2
create table if not exists k_league_2 (
  id bigint generated by default as identity primary key,
  시즌 text not null,
  라운드 integer not null,
  날짜 text,
  시간 text,
  홈 text not null,
  홈순위 text,
  홈점수 text,
  원정점수 text,
  원정순위 text,
  원정 text not null,
  승 text,
  무 text,
  패 text,
  오버 text,
  오버라인 text,
  언더 text,
  핸디캡홈 text,
  핸디캡라인 text,
  핸디캡원정 text,
  created_at timestamptz default now(),
  unique(시즌, 날짜, 시간, 홈, 원정)
);

-- premier_league
create table if not exists premier_league (
  id bigint generated by default as identity primary key,
  시즌 text not null,
  라운드 integer not null,
  날짜 text,
  시간 text,
  홈 text not null,
  홈순위 text,
  홈점수 text,
  원정점수 text,
  원정순위 text,
  원정 text not null,
  승 text,
  무 text,
  패 text,
  오버 text,
  오버라인 text,
  언더 text,
  핸디캡홈 text,
  핸디캡라인 text,
  핸디캡원정 text,
  created_at timestamptz default now(),
  unique(시즌, 날짜, 시간, 홈, 원정)
);

-- bundesliga
create table if not exists bundesliga (
  id bigint generated by default as identity primary key,
  시즌 text not null,
  라운드 integer not null,
  날짜 text,
  시간 text,
  홈 text not null,
  홈순위 text,
  홈점수 text,
  원정점수 text,
  원정순위 text,
  원정 text not null,
  승 text,
  무 text,
  패 text,
  오버 text,
  오버라인 text,
  언더 text,
  핸디캡홈 text,
  핸디캡라인 text,
  핸디캡원정 text,
  created_at timestamptz default now(),
  unique(시즌, 날짜, 시간, 홈, 원정)
);

-- laliga
create table if not exists laliga (
  id bigint generated by default as identity primary key,
  시즌 text not null,
  라운드 integer not null,
  날짜 text,
  시간 text,
  홈 text not null,
  홈순위 text,
  홈점수 text,
  원정점수 text,
  원정순위 text,
  원정 text not null,
  승 text,
  무 text,
  패 text,
  오버 text,
  오버라인 text,
  언더 text,
  핸디캡홈 text,
  핸디캡라인 text,
  핸디캡원정 text,
  created_at timestamptz default now(),
  unique(시즌, 날짜, 시간, 홈, 원정)
);

-- j1_league
create table if not exists j1_league (
  id bigint generated by default as identity primary key,
  시즌 text not null,
  라운드 integer not null,
  날짜 text,
  시간 text,
  홈 text not null,
  홈순위 text,
  홈점수 text,
  원정점수 text,
  원정순위 text,
  원정 text not null,
  승 text,
  무 text,
  패 text,
  오버 text,
  오버라인 text,
  언더 text,
  핸디캡홈 text,
  핸디캡라인 text,
  핸디캡원정 text,
  created_at timestamptz default now(),
  unique(시즌, 날짜, 시간, 홈, 원정)
);

-- serie_a
create table if not exists serie_a (
  id bigint generated by default as identity primary key,
  시즌 text not null,
  라운드 integer not null,
  날짜 text,
  시간 text,
  홈 text not null,
  홈순위 text,
  홈점수 text,
  원정점수 text,
  원정순위 text,
  원정 text not null,
  승 text,
  무 text,
  패 text,
  오버 text,
  오버라인 text,
  언더 text,
  핸디캡홈 text,
  핸디캡라인 text,
  핸디캡원정 text,
  created_at timestamptz default now(),
  unique(시즌, 날짜, 시간, 홈, 원정)
);
